proyectopdf_1_plantilla/Models/ErrorViewModel.cs
namespace proyectopdf_1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

proyectopdf_1_plantilla/Controllers/CategoriaController.cs
using Microsoft.AspNetCore.Mvc;

namespace proyectopdf_1.Controllers
{
    public class CategoriaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

proyectopdf_1_plantilla/Controllers/DashBoardController.cs
using Microsoft.AspNetCore.Mvc;

namespace proyectopdf_1.Controllers
{
    public class DashBoardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

proyectopdf_1_plantilla/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using proyectopdf_1.Models;

namespace proyectopdf_1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        //Agregamos un ASP metod
        public IActionResult Perfil()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

proyectopdf_1_plantilla/Controllers/NegocioController.cs
using Microsoft.AspNetCore.Mvc;

namespace proyectopdf_1.Controllers
{
    public class NegocioController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

proyectopdf_1_plantilla/Controllers/ProductoController.cs
using Microsoft.AspNetCore.Mvc;

namespace proyectopdf_1.Controllers
{
    public class ProductoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

proyectopdf_1_plantilla/Controllers/ReporteController.cs
using Microsoft.AspNetCore.Mvc;

namespace proyectopdf_1.Controllers
{
    public class ReporteController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

proyectopdf_1_plantilla/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Mvc;

namespace proyectopdf_1.Controllers
{
    public class UsuarioController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

proyectopdf_1_plantilla/Controllers/VentaController.cs
using Microsoft.AspNetCore.Mvc;

namespace proyectopdf_1.Controllers
{
    public class VentaController : Controller
    {
        public IActionResult NuevaVenta()
        {
            return View();
        }

        public IActionResult HistorialVenta()
        {
            return View();
        }
    }
}

proyectopdf_1_plantilla/Views/Categoria/Index.cshtml
@{
    ViewData["Title"] = "Categoria";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Estilos {
    <!-- ============================================================
    =ESTILOS PARA ESTA PAGINA
    ===============================================================-->
    <link rel="stylesheet" href="~/vendor/datatables/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/vendor/datatables/extensiones/css/responsive.dataTables.min.css">
    <link rel="stylesheet" href="~/vendor/datatables/extensiones/css/buttons.dataTables.min.css">
}


<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3 bg-second-primary">
        <h6 class="m-0 font-weight-bold text-white">Lista de Categorias</h6>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-sm-3">
                <button class="btn btn-success" data-toggle="modal" data-target="#modalData"><i class="fas fa-plus-circle"></i> Nueva Categoria</button>
            </div>
        </div>
        <hr />
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-bordered" id="tbdata" cellspacing="0" style="width:100%">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Descripcion</th>
                            <th>Estado</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>1</td>
                            <td>Descripcion 1</td>
                            <td><span class="badge badge-info">Activo</span></td>
                            <td>
                                <button class="btn btn-primary btn-sm">
                                    <i class="fas fa-pencil-alt"></i>
                                </button>
                                <button class="btn btn-danger btn-sm">
                                    <i class="fas fa-trash-alt"></i>
                                </button>
                            </td>
                        </tr>
                        <tr>
                            <td>2</td>
                            <td>Descripcion 2</td>
                            <td><span class="badge badge-danger">No Activo</span></td>
                            <td>
                                <button class="btn btn-primary btn-sm">
                                    <i class="fas fa-pencil-alt"></i>
                                </button>
                                <button class="btn btn-danger btn-sm">
                                    <i class="fas fa-trash-alt"></i>
                                </button>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!--  Modal-->
<div class="modal fade" id="modalData" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h6>Detalle Categoria</h6>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
                    <input type="hidden" value="0" id="txtId">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-row">
                                <div class="form-group col-sm-6">
                                    <label for="txtDescripcion">Descripcion</label>
                                    <input type="text" class="form-control form-control-sm" id="txtDescripcion">
                                </div>
                                <div class="form-group col-sm-6">
                                    <label for="cboEstado">Estado</label>
                                    <select class="form-control form-control-sm" id="cboEstado">
                                        <option value="1">Activo</option>
                                        <option value="0">No Activo</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary btn-sm" type="button" id="btnGuardar">Guardar</button>
                <button class="btn btn-danger btn-sm" type="button" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    <!-- ============================================================
    =SCRIPTS PARA ESTA PAGINA
    ===============================================================-->
    <script src="~/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="~/vendor/datatables/dataTables.bootstrap4.min.js"></script>

    <script src="~/vendor/datatables/extensiones/js/dataTables.responsive.min.js"></script>

    <script src="~/vendor/datatables/extensiones/js/dataTables.buttons.min.js"></script>
    <script src="~/vendor/datatables/extensiones/js/jszip.min.js"></script>
    <script src="~/vendor/datatables/extensiones/js/buttons.html5.min.js"></script>
    <script src="~/vendor/datatables/extensiones/js/buttons.print.min.js"></script>

    <!-- SOLO ES DE EJEMPLO - IGNORAR -->
    <script src="~/js/vistas/datatables-demo.js"></script>
}
    

proyectopdf_1_plantilla/Views/DashBoard/Index.cshtml
@*1.1.Referencia de estilos la tiene la "masterpage"*@
@{
    @*1.5. Modificamos esto*@
    ViewData["Title"] = "DashBoard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*1.0.Que es el nombre del controlador [<h1>DashBoard</h1>]*@
@*1.2.Copiar contwnido de "PF"*@


<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
</div>

<!-- Content Row -->
<div class="row">

    <!-- Total de ventas -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            Total de Ventas
                        </div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800" id="totalVenta">30</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-shopping-basket fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Total de Ingresos -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-success shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                            Total de Ingresos
                        </div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800" id="totalIngresos">$215,000</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Total de Productos -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-info shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                            Total de Productos
                        </div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800" id="totalProductos">50</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>



    <!-- Total de Categorias -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-warning shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                            Total de Categorias
                        </div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800" id="totalCategorias">18</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-tags fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Content Row -->

<div class="row">

    <!-- Area Chart - Ventas de los ultimos 7 días -->
    <div class="col-xl-8 col-lg-7">
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div class="card-header py-3 bg-second-primary">
                <h6 class="m-0 font-weight-bold text-white">Ventas de los ultimos 7 días</h6>
            </div>
            <!-- Card Body -->
            <div class="card-body">
                <div class="chart-area" style="height: 350px !important;">
                    <canvas id="charVentas"></canvas>
                </div>
            </div>
        </div>
    </div>

    <!-- Pie Chart - Productos más vendidos-->
    <div class="col-xl-4 col-lg-5">
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div class="card-header py-3 bg-second-primary">
                <h6 class="m-0 font-weight-bold text-white">Productos más vendidos</h6>
            </div>
            <!-- Card Body -->
            <div class="card-body">
                <div class="chart-pie" style="height: 350px !important ;">
                    <canvas id="charProductos"></canvas>
                </div>
            </div>
        </div>
    </div>
</div>



@section Scripts{
    @*1.3.Copiar estilos, no en head esta vez sino que en bloque de script*@
    @*1.4. Entonces lo vamos a comentar de esta forma porque es la sección que está en el "Layaout", es decir desde el Layout copiaremos el nombre "Script"*@
    <!-- ============================================================
    =SCRIPTS PARA ESTA PAGINA
    ===============================================================-->
    <script src="~/vendor/chart.js/Chart.min.js"></script>

    <!-- SOLO ES DE EJEMPLO - IGNORAR -->
    <script src="~/js/vistas/chart-bar-demo.js"></script>
    <script src="~/js/vistas/chart-pie-demo.js"></script>
}

proyectopdf_1_plantilla/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

proyectopdf_1_plantilla/Views/Home/Perfil.cshtml
@{
    ViewData["Title"] = "Perfil";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-sm-4">

        <div class="card shadow mb-4">
            <div class="card-header py-3 bg-second-primary">
                <h6 class="m-0 font-weight-bold text-white"><i class="fas fa-user"></i> Mis Datos</h6>
            </div>
            <div class="card-body">

                <form>
                    <div class="form-row">
                        <div class="form-group col-sm-12">
                            <img id="imgFoto" src="https://images.unsplash.com/photo-1519648023493-d82b5f8d7b8a?w=300" class="rounded mx-auto d-block" style="width: 200px; height: 200px;">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-sm-12">
                            <label for="txtNombre">Nombre</label>
                            <input type="text" class="form-control form-control-sm" disabled id="txtNombre">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-sm-12">
                            <label for="txtCorreo">Correo</label>
                            <input type="email" class="form-control form-control-sm" id="txtCorreo">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-sm-12">
                            <label for="txTelefono">Telefono</label>
                            <input type="text" class="form-control form-control-sm" id="txTelefono">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-sm-12">
                            <label for="txtRol">Rol</label>
                            <input type="text" class="form-control form-control-sm" disabled id="txtRol">
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-12">
                            <button type="button" class="btn btn-success btn-sm btn-block" id="btnGuardarCambios">Guardar Cambios</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

    </div>
    <div class="col-sm-4">
        <div class="card shadow mb-4">
            <div class="card-header py-3 bg-second-primary">
                <h6 class="m-0 font-weight-bold text-white"><i class="fas fa-key"></i> Cambiar Contraseña</h6>
            </div>
            <div class="card-body">
                <form>
                    <div class="form-row">
                        <div class="form-group col-sm-12">
                            <label for="txtClaveActual">Contraseña Actual</label>
                            <input type="password" class="form-control form-control-sm input-validar" id="txtClaveActual" name="Clave Actual">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-sm-12">
                            <label for="txtClaveNueva">Nueva Contraseña</label>
                            <input type="password" class="form-control form-control-sm input-validar" id="txtClaveNueva" name="Clave Nueva">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-sm-12">
                            <label for="txtConfirmarClave">Confirmar Contraseña</label>
                            <input type="password" class="form-control form-control-sm input-validar" id="txtConfirmarClave" name="Confirmar Clave">
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-12">
                            <button type="button" class="btn btn-success btn-sm btn-block" id="btnCambiarClave">Guardar Cambios</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

proyectopdf_1_plantilla/Views/Shared/_Layout.cshtml
<!-- Pagina "master page"-->
<!DOCTYPE html>
<html lang="en">
<head>
    @*Copiamos head*@
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Mi Tienda - @ViewData["Title"]</title>

    @*Custom fonts for this template-->*@
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template--> 
    @*Cambiaremos las referencias, agrgamos simbolo mas, los cual accede a la raiz del proyecto "wwwroot"*@
    <link href="~/css/sb-admin-2.css" rel="stylesheet">
    <link href="~/vendor/toastr/toastr.min.css" rel="stylesheet">
    <link href="~/vendor/sweetalert/sweetalert.css" rel="stylesheet">
    @*"Render" para los estilos*@
    @await RenderSectionAsync("Estilos", required: false)
</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="#">
                <div class="sidebar-brand-icon">
                    <i class="fas fa-desktop"></i>
                </div>
                <div class="sidebar-brand-text mx-3">MI TIENDA</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">
            <!-- Nav Item - Dashboard -->
            @*2.1. Aquí trabajeremos con "Dashboard"*@
            @*2.1. Luego de esto comenzaremos a crear los "contoladores" para crear las "vistas"*@
            @*2.2. Clic derecho en "Controller", agregar nuevo "Controller"*@
            @*2.3. Contoller en blanco*@
            @*2.4. En "HomeController1.cs" reemplazamos la palabra "Home" por la palabra "DashBoard"*@
            @*2.5. Utilizaremos Metodo Index, cliqueamos click derecho en "public IActionResult Index()", "Vista de Razor", 
            cambiamos la pagina de diseño por la que está en "View ->Shared->Layout.cshtml"*@
            <li class="nav-item">
                @*Aquí en "Index.html" escribimos "@Url.Action("Index","DashBoard")"
                es decir "Metodo" y "Controlador"*@
                <a class="nav-link" href="@Url.Action("Index", "DashBoard")">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span></a>
            </li>


            @*Menu Usarios*@
            <!-- Nav Item - Administración Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseAdministracion">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Administración</span>
                </a>
                <div id="collapseAdministracion" class="collapse" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        @*Escribimos nombre de: "Metodo" y "Controlador"*@
                        <a class="collapse-item" href="@Url.Action("Index", "Usuario")">Usuarios</a>
                        <a class="collapse-item" href="@Url.Action("Index", "Negocio")">Negocio</a>
                    </div>
                </div>
            </li>


            @*Menu  Categoria, Inventario*@
            <!-- Nav Item - Inventario Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseInventario">
                    <i class="fas fa-fw fa-clipboard-list"></i>
                    <span>Inventario</span>
                </a>
                <div id="collapseInventario" class="collapse" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="@Url.Action("Index", "Categoria")">Categorias</a>
                        <a class="collapse-item" href="@Url.Action("Index", "Producto")">Productos</a>
                    </div>
                </div>
            </li>


            @*Menu Venta*@
            <!-- Nav Item - Venta Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseVenta">
                    <i class="fas fa-fw fa-tags"></i>
                    <span>Ventas</span>
                </a>
                <div id="collapseVenta" class="collapse" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="@Url.Action("NuevaVenta", "Venta")">Nueva Venta</a>
                        <a class="collapse-item" href="@Url.Action("HistorialVenta", "Venta")">Historial Venta</a>
                    </div>
                </div>
            </li>


            <!-- Nav Item - Reportes Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseReportes">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>Reportes</span>
                </a>
                <div id="collapseReportes" class="collapse" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="@Url.Action("Index", "Reporte")">Reporte de Ventas</a>
                    </div>
                </div>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">
            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>
        </ul><!-- End of Sidebar -->
        
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Douglas McGee</span>
                                <img class="img-profile rounded-circle"
                                     src="https://images.unsplash.com/photo-1519648023493-d82b5f8d7b8a?w=300">
                            </a>

                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="@Url.Action("Perfil", "Home")">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Perfil
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Salir
                                </a>
                            </div>
                        </li>

                    </ul>
                </nav><!-- End of Topbar -->
                

                <!-- Begin Page Content -->


                <!-- /.container-fluid -->
                <div class="container-fluid">
                    @*Copiamos  este "@RenderBody()"*@
                    @RenderBody()
                </div>
                
            </div><!-- End of Main Content -->
            
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; YourWebsite 2025</span>
                    </div>
                </div>
            </footer><!-- End of Footer -->
            
        </div><!-- End of Content Wrapper -->
        
    </div><!-- End of Page Wrapper -->
    
    <!-- Bootstrap core JavaScript-->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.js"></script>
    <script src="~/vendor/toastr/toastr.min.js"></script>
    <script src="~/vendor/sweetalert/sweetalert.js"></script>
    <script src="~/vendor/loadingoverlay/loadingoverlay.min.js"></script>
    @*Copiamos  el "RenderSectionAsync"*@
   
</body>

</html>
@*Secciones que estaremos utilizando*@
@*Matenemos "render body" además de "RenderSectionAsync" además de @RenderBody()*@
@await RenderSectionAsync("Scripts", required: false)